# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

def ui_components_and_helper_pods
    pod 'Material'
    pod 'SnapKit'
    pod 'DrawerController'
    pod 'DGElasticPullToRefresh'
    pod 'Charts'
end

target 'Stellargate' do

  # Pods for jupiter
  ui_components_and_helper_pods
  
  pod 'R.swift'
  pod 'stellar-ios-mac-sdk'

  target 'StellargateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StellargateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
