# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

def ui_components_and_helper_pods
    pod 'Material'
    pod 'SnapKit'
    pod 'KWDrawerController'
    pod 'DGElasticPullToRefresh'
    pod 'Charts'
    pod 'LTMorphingLabel'
    pod 'TTTAttributedLabel'
end

target 'Lumenshine' do

  # Pods for jupiter
  ui_components_and_helper_pods
  
  pod 'R.swift'
  pod 'stellar-ios-mac-sdk', '~> 1.1.4'
  pod 'IQKeyboardManagerSwift'
  pod 'OneTimePassword'
  pod 'SwiftRichString'

  target 'LumenshineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LumenshineUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
