# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

def ui_components_and_helper_pods
    pod 'Material'
    pod 'SnapKit'
    pod 'KWDrawerController', :git => 'https://github.com/chelemen-razvan/KWDrawerController.git'
    pod 'DGElasticPullToRefresh', :git => 'https://github.com/sammygutierrez/DGElasticPullToRefresh.git'
    pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :commit => '4fca1f7a027c69782522416ef73d9bb92119d1d3'
    pod 'LTMorphingLabel'
    pod 'TTTAttributedLabel'
end

target 'Lumenshine' do

  # Pods for jupiter
  ui_components_and_helper_pods
  
  pod 'R.swift'
  pod 'stellar-ios-mac-sdk', '~> 1.2.1'
  pod 'OneTimePassword'
  pod 'SwiftRichString'
  
  pod 'IQKeyboardManagerSwift'

  target 'LumenshineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LumenshineUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
