# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

def ui_components_and_helper_pods
    pod 'Material'
    pod 'SnapKit'
    pod 'KWDrawerController', :git => 'https://github.com/chelemen-razvan/KWDrawerController.git', :commit => 'f53f97683e87c016f415e250a7b019c81e524bf6'
    pod 'DGElasticPullToRefresh', :git => 'https://github.com/Lateblumer88/DGElasticPullToRefresh', :branch => 'Feature/Swift5Support'
    pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :commit => 'e8505930018668b73500203afc13bb92fa585f8a'
    pod 'LTMorphingLabel', :git => 'https://github.com/lexrus/LTMorphingLabel.git', :commit => '711a91a709570a481f3f6bd902b728cbabdd65a0'
    pod 'TTTAttributedLabel'
    pod 'M13Checkbox'
end

target 'Lumenshine' do

  # Pods for jupiter
  ui_components_and_helper_pods
  
  pod 'R.swift', '~> 5.0.3'
  pod 'stellar-ios-mac-sdk', '~> 1.6.4'
  pod 'OneTimePassword'
  pod 'SwiftRichString'
  pod 'Starscream', :git => 'https://github.com/Soneso/Starscream.git'
  pod 'ReachabilitySwift'
  
  pod 'IQKeyboardManagerSwift'

  target 'LumenshineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LumenshineUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
